# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'quantum.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_quantumwidget(object):
    def setupUi(self, quantumwidget):
        quantumwidget.setObjectName("quantumwidget")
        quantumwidget.resize(671, 168)
        quantumwidget.setStyleSheet("QScrollArea{\n"
"    border: 0px solid;\n"
"    border-right-width: 1px;\n"
"    border-right-color: #dcdbdc;\n"
"    background-color: #f5f5f7;\n"
"}\n"
"    QScrollBar:vertical {\n"
"    border: none;\n"
"    background: #f5f5f7;\n"
"    width: 10px;\n"
"    margin: 0px 0 0px 0;\n"
"    }\n"
"    QScrollBar::handle:vertical {\n"
"    background: Gainsboro;\n"
"    min-height: 20px;\n"
"    border-radius: 5px;\n"
"    border: none;\n"
"    }\n"
"    QScrollBar::add-line:vertical {\n"
"    border: 0px solid grey;\n"
"    background: #32CC99;\n"
"    height: 0px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"    }\n"
"    QScrollBar::sub-line:vertical {\n"
"    border: 0px solid grey;\n"
"    background: #32CC99;\n"
"    height: 0px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"    }\n"
"    QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"    width: 0px;\n"
"    height: 0px;\n"
"    }")
        self.verticalLayout = QtWidgets.QVBoxLayout(quantumwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(quantumwidget)
        font = QtGui.QFont()
        font.setFamily("Hitmo2.0")
        font.setKerning(False)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(24, 90, 119)")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.nbits = QtWidgets.QLineEdit(quantumwidget)
        font = QtGui.QFont()
        font.setFamily("Hitmo2.0")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.nbits.setFont(font)
        self.nbits.setStyleSheet("font: 10pt \"Hitmo2.0\";\n"
"padding: 0px 5px 0px 5px;\n"
"border: 1px groove gray;\n"
"border-radius: 10px;")
        self.nbits.setObjectName("nbits")
        self.horizontalLayout.addWidget(self.nbits)
        self.horizontalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(quantumwidget)
        font = QtGui.QFont()
        font.setFamily("Hitmo2.0")
        font.setKerning(False)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(24, 90, 119)")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.optimizer = QtWidgets.QLineEdit(quantumwidget)
        font = QtGui.QFont()
        font.setFamily("Hitmo2.0")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.optimizer.setFont(font)
        self.optimizer.setStyleSheet("font: 10pt \"Hitmo2.0\";\n"
"padding: 0px 5px 0px 5px;\n"
"border: 1px groove gray;\n"
"border-radius: 10px;")
        self.optimizer.setObjectName("optimizer")
        self.horizontalLayout_2.addWidget(self.optimizer)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(quantumwidget)
        font = QtGui.QFont()
        font.setFamily("Hitmo2.0")
        font.setKerning(False)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(24, 90, 119)")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.result = QtWidgets.QLabel(quantumwidget)
        font = QtGui.QFont()
        font.setFamily("Hitmo2.0")
        font.setKerning(False)
        self.result.setFont(font)
        self.result.setText("")
        self.result.setObjectName("result")
        self.horizontalLayout_3.addWidget(self.result)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 1)
        self.horizontalLayout_4.setStretch(2, 3)
        self.horizontalLayout_4.setStretch(3, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.scrollArea = QtWidgets.QScrollArea(quantumwidget)
        self.scrollArea.setStyleSheet("QScrollArea {\n"
"    border: 0px solid;\n"
"}\n"
"\n"
"QScrollBar::vertical {\n"
"    border: none;\n"
"    width: 10px;\n"
"    margin: 3px 0 3px 0;\n"
"}\n"
"\n"
"QScrollBar::horizontal {\n"
"    border: none;\n"
"    height: 10px;\n"
"    margin: 0 3px 0 3px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical,\n"
"QScrollBar::handle:horizontal {\n"
"    background: #185a77;\n"
"    border-radius: 5px;\n"
"    border: none;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::add-line:horizontal {\n"
"    border: 0px solid grey;\n"
"    height: 0px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical,\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: 0px solid grey;\n"
"    height: 0px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical,\n"
"QScrollBar::sub-page:vertical,\n"
"QScrollBar::add-page:horizontal,\n"
"QScrollBar::sub-page:horizontal {\n"
"    background: #f0f5f7;\n"
"    width: 0px;\n"
"    height: 0px;\n"
"}")
        self.scrollArea.setLineWidth(1)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 649, 109))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.figurelayout = QtWidgets.QGridLayout()
        self.figurelayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.figurelayout.setObjectName("figurelayout")
        self.verticalLayout_2.addLayout(self.figurelayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(quantumwidget)
        QtCore.QMetaObject.connectSlotsByName(quantumwidget)

    def retranslateUi(self, quantumwidget):
        _translate = QtCore.QCoreApplication.translate
        quantumwidget.setWindowTitle(_translate("quantumwidget", "Form"))
        self.label.setText(_translate("quantumwidget", "Nbits"))
        self.label_2.setText(_translate("quantumwidget", "Optimizer"))
        self.label_3.setText(_translate("quantumwidget", "Result"))
import assets.assets_rc
