# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'classic.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_classicwidget(object):
    def setupUi(self, classicwidget):
        classicwidget.setObjectName("classicwidget")
        classicwidget.resize(671, 169)

        self.retranslateUi(classicwidget)
        QtCore.QMetaObject.connectSlotsByName(classicwidget)

    def retranslateUi(self, classicwidget):
        _translate = QtCore.QCoreApplication.translate
        classicwidget.setWindowTitle(_translate("classicwidget", "Form"))
