# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'quantum.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_quantumwidget(object):
    def setupUi(self, quantumwidget):
        quantumwidget.setObjectName("quantumwidget")
        quantumwidget.resize(671, 168)

        self.retranslateUi(quantumwidget)
        QtCore.QMetaObject.connectSlotsByName(quantumwidget)

    def retranslateUi(self, quantumwidget):
        _translate = QtCore.QCoreApplication.translate
        quantumwidget.setWindowTitle(_translate("quantumwidget", "Form"))
