# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'task.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_taskwidget(object):
    def setupUi(self, taskwidget):
        taskwidget.setObjectName("taskwidget")
        taskwidget.resize(208, 417)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(taskwidget)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(taskwidget)
        font = QtGui.QFont()
        font.setFamily("Hitmo2.0")
        font.setKerning(False)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(24, 90, 119)")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.stockprice = QtWidgets.QLineEdit(taskwidget)
        font = QtGui.QFont()
        font.setFamily("Hitmo2.0")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.stockprice.setFont(font)
        self.stockprice.setStyleSheet("font: 10pt \"Hitmo2.0\";\n"
"padding: 0px 5px 0px 5px;\n"
"border: 1px groove gray;\n"
"border-radius: 10px;")
        self.stockprice.setObjectName("stockprice")
        self.verticalLayout.addWidget(self.stockprice)
        self.verticalLayout_7.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(taskwidget)
        font = QtGui.QFont()
        font.setFamily("Hitmo2.0")
        font.setKerning(False)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(24, 90, 119)")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.strikeprice = QtWidgets.QLineEdit(taskwidget)
        font = QtGui.QFont()
        font.setFamily("Hitmo2.0")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.strikeprice.setFont(font)
        self.strikeprice.setStyleSheet("font: 10pt \"Hitmo2.0\";\n"
"padding: 0px 5px 0px 5px;\n"
"border: 1px groove gray;\n"
"border-radius: 10px;")
        self.strikeprice.setObjectName("strikeprice")
        self.verticalLayout_2.addWidget(self.strikeprice)
        self.verticalLayout_7.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(taskwidget)
        font = QtGui.QFont()
        font.setFamily("Hitmo2.0")
        font.setKerning(False)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(24, 90, 119)")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.maturity = QtWidgets.QLineEdit(taskwidget)
        font = QtGui.QFont()
        font.setFamily("Hitmo2.0")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.maturity.setFont(font)
        self.maturity.setStyleSheet("font: 10pt \"Hitmo2.0\";\n"
"padding: 0px 5px 0px 5px;\n"
"border: 1px groove gray;\n"
"border-radius: 10px;")
        self.maturity.setObjectName("maturity")
        self.verticalLayout_3.addWidget(self.maturity)
        self.verticalLayout_7.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(taskwidget)
        font = QtGui.QFont()
        font.setFamily("Hitmo2.0")
        font.setKerning(False)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(24, 90, 119)")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.marketrate = QtWidgets.QLineEdit(taskwidget)
        font = QtGui.QFont()
        font.setFamily("Hitmo2.0")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.marketrate.setFont(font)
        self.marketrate.setStyleSheet("font: 10pt \"Hitmo2.0\";\n"
"padding: 0px 5px 0px 5px;\n"
"border: 1px groove gray;\n"
"border-radius: 10px;")
        self.marketrate.setObjectName("marketrate")
        self.verticalLayout_4.addWidget(self.marketrate)
        self.verticalLayout_7.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(taskwidget)
        font = QtGui.QFont()
        font.setFamily("Hitmo2.0")
        font.setKerning(False)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(24, 90, 119)")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.volatility = QtWidgets.QLineEdit(taskwidget)
        font = QtGui.QFont()
        font.setFamily("Hitmo2.0")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.volatility.setFont(font)
        self.volatility.setStyleSheet("font: 10pt \"Hitmo2.0\";\n"
"padding: 0px 5px 0px 5px;\n"
"border: 1px groove gray;\n"
"border-radius: 10px;")
        self.volatility.setObjectName("volatility")
        self.verticalLayout_5.addWidget(self.volatility)
        self.verticalLayout_7.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_6 = QtWidgets.QLabel(taskwidget)
        font = QtGui.QFont()
        font.setFamily("Hitmo2.0")
        font.setKerning(False)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(24, 90, 119)")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.accuracy = QtWidgets.QLineEdit(taskwidget)
        font = QtGui.QFont()
        font.setFamily("Hitmo2.0")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.accuracy.setFont(font)
        self.accuracy.setStyleSheet("font: 10pt \"Hitmo2.0\";\n"
"padding: 0px 5px 0px 5px;\n"
"border: 1px groove gray;\n"
"border-radius: 10px;")
        self.accuracy.setObjectName("accuracy")
        self.verticalLayout_6.addWidget(self.accuracy)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)

        self.retranslateUi(taskwidget)
        QtCore.QMetaObject.connectSlotsByName(taskwidget)

    def retranslateUi(self, taskwidget):
        _translate = QtCore.QCoreApplication.translate
        taskwidget.setWindowTitle(_translate("taskwidget", "Form"))
        self.label.setText(_translate("taskwidget", "Stock Price / ￥"))
        self.label_2.setText(_translate("taskwidget", "Strike Price / ￥"))
        self.label_3.setText(_translate("taskwidget", "Maturity / y"))
        self.label_4.setText(_translate("taskwidget", "risk-free market rate"))
        self.label_5.setText(_translate("taskwidget", "volatility"))
        self.label_6.setText(_translate("taskwidget", "accuracy"))
import assets.assets_rc
